export const ADD_PASSWORD = "ADD_PASSWORD";
export const EDIT_CONTACT = 'EDIT_CONTACT';
export const UPDATE_PASSWORD = 'UPDATE_PASSWORD';
export const DELETE_PASSWORD = 'DELETE_PASSWORD';
export const SELECT_ALL = 'SELECT_ALL';
export const DELETE_ALL = 'DELETE_ALL';
export const DELETE_SELECTED_PASSWORDS = 'DELETE_SELECTED_PASSWORDS';